apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-iam-root-sh
  namespace: dev
spec:
  secretName: dev-iam-root-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dev.iamroot.sh
  dnsNames:
  - dev.iamroot.sh
